baseURL = 'https://stephencz.com/'
languageCode = 'en-us'
title = 'Stephen Czekalski'

[params]
  [params.author]
    name = "Stephen Czekalski"
    job = "Data Analyst"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    style = 'catppuccin-latte'
    lineNos = true
